"""initial schema

Revision ID: 029ebd343e4c
Revises: 
Create Date: 2026-08-08 05:37:20.960486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029ebd343e4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('api_key_hash', sa.String(length=64), nullable=True),
    sa.Column('api_key_prefix', sa.String(length=24), nullable=True),
    sa.Column('api_key_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('oauth_provider', sa.String(length=32), nullable=True),
    sa.Column('oauth_subject', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('oauth_provider', 'oauth_subject', name='uq_users_oauth_identity')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_api_key_hash'), ['api_key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('ml_learning_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('optimization_id', sa.String(length=128), nullable=False),
    sa.Column('prompt_features', sa.JSON(), nullable=True),
    sa.Column('optimization_result', sa.JSON(), nullable=True),
    sa.Column('quality_metrics', sa.JSON(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ml_learning_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_learning_events'))
    )
    with op.batch_alter_table('ml_learning_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_learning_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_learning_events_optimization_id'), ['optimization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_learning_events_user_id'), ['user_id'], unique=False)

    op.create_table('ml_performance_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_optimizations', sa.Integer(), nullable=False),
    sa.Column('average_quality', sa.Float(), nullable=False),
    sa.Column('average_token_reduction', sa.Float(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('quality_trend', sa.Float(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ml_performance_snapshots_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_performance_snapshots'))
    )
    with op.batch_alter_table('ml_performance_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_performance_snapshots_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_performance_snapshots_user_id'), ['user_id'], unique=False)

    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tokens_before', sa.Integer(), nullable=False),
    sa.Column('tokens_after', sa.Integer(), nullable=False),
    sa.Column('kwh_before', sa.Float(), nullable=False),
    sa.Column('kwh_after', sa.Float(), nullable=False),
    sa.Column('co2_g_before', sa.Float(), nullable=False),
    sa.Column('co2_g_after', sa.Float(), nullable=False),
    sa.Column('retention_score', sa.Float(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('strategy', sa.String(length=32), nullable=True),
    sa.Column('optimizations_applied', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_receipts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipts'))
    )
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipts_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipts_receipt_id'), ['receipt_id'], unique=True)
        batch_op.create_index('ix_receipts_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipts_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_receipts_user_model', ['user_id', 'model'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_index('ix_receipts_user_model')
        batch_op.drop_index(batch_op.f('ix_receipts_user_id'))
        batch_op.drop_index('ix_receipts_user_created')
        batch_op.drop_index(batch_op.f('ix_receipts_receipt_id'))
        batch_op.drop_index(batch_op.f('ix_receipts_model'))
        batch_op.drop_index(batch_op.f('ix_receipts_created_at'))

    op.drop_table('receipts')
    with op.batch_alter_table('ml_performance_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_performance_snapshots_user_id'))
        batch_op.drop_index(batch_op.f('ix_ml_performance_snapshots_created_at'))

    op.drop_table('ml_performance_snapshots')
    with op.batch_alter_table('ml_learning_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_learning_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_ml_learning_events_optimization_id'))
        batch_op.drop_index(batch_op.f('ix_ml_learning_events_created_at'))

    op.drop_table('ml_learning_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_public_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.drop_index(batch_op.f('ix_users_api_key_hash'))

    op.drop_table('users')
    # ### end Alembic commands ###
